app/models.py
# database modeles
from . import db

# class User(db.Model):
#     __tablename__ = 'TD_user'
#     id = db.Column(db.Integer, primary_key = True)
#     email = db.Column(db.String(20))
#     password = db.Column(db.Integer)

#     def __repr__(self):
#         return '< email: '+self.email+' user id: '+self.id+' >'

class Admin(db.Model):
    __tablename__ = 'TD_admin'
    id = db.Column(db.Integer, primary_key = True)
    admin_id = db.Column(db.String(20))
    admin_password = db.Column(db.String(20))

    def __repr__(self):
        return '<admin_id: '+self.admin_id+', password: '+self.admin_password+'>'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

# for login page
class Login_Form(FlaskForm):
    login_form_id = StringField('Email', validators=[DataRequired()])
    login_form_pass = StringField('Password', validators=[DataRequired()])
    login_form_submit = SubmitField('Login')

# for register page
# class Registration_Form(FlaskForm):
#     registration_form_name = StringField('Name', validators=[DataRequired()])
#     registration_form_email = StringField('Email', validators=[DataRequired()])
#     registration_form_pass = StringField('Password', validators=[DataRequired()])
#     registration_form_cpass = StringField('Confirm Password', validators=[DataRequired()])
#     registration_form_submit = SubmitField('Create Account')

app/__init__.py
from config import config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

# application instances 
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    #db.create_all()

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, url_for, redirect
from . import main
from .forms import Login_Form
# from .. import db
from ..models import Admin, db

# all routes of page

#------------------------------------------------------------- index
@main.route('/')
@main.route('/home/')
def index():
    return render_template('index.html')


#------------------------------------------------------------- blog
@main.route('/blog/')
def blog():
    return render_template('blog.html')


#------------------------------------------------------------- posts
@main.route('/post/')
def post():
    return render_template('post.html')

# ----------------------------------------------------------- Admin
@main.route('/admin/', methods=['GET','POST'])
def admin():
    form = Login_Form()

    # GET request action
    if form.validate_on_submit():
        print('-'*10)
        print('Admin Id: '+form.login_form_id.data)
        print('Password: '+form.login_form_pass.data)
        print('-'*10)


        # storing in database
        my_user = Admin(admin_id = form.login_form_id.data, admin_password = form.login_form_pass.data)
        db.session.add(my_user)
        db.session.commit()

        return render_template('index.html')
    return render_template('admin.html', form=form)

# ----------------------------------------------------------- login
# @main.route('/login/', methods=['GET','POST'])
# def login():
#     form = Login_Form()

#     # GET request action
#     if form.validate_on_submit():
#         print("Email: "+form.login_form_email.data)
#         print("Password: "+form.login_form_pass.data)

#         # storing in database
#         # db.create_all()
#         my_user = User(email = form.login_form_email.data, password = form.login_form_pass.data)
#         db.session.add(my_user)
#         db.session.commit()
        
#         # reseting all data to empty str
#         form.login_form_email.data=''
#         form.login_form_pass.data=''

#         # redirect session
#         return redirect(url_for('main.index'))

#     return render_template('login.html', form=form)


# # ------------------------------------------------------------ registration
# @main.route('/registration/', methods=['GET', 'POST'])
# def registration():
#     form = Registration_Form()

#     # GET request action
#     if form.validate_on_submit():
#         print('Name: '+form.registration_form_name.data)
#         print('Email: '+form.registration_form_email.data)
#         print('Pass: '+form.registration_form_pass.data)

#         # reseting all data to empty str
#         form.registration_form_name.data=''
#         form.registration_form_email.data=''
#         form.registration_form_pass.data=''
#         form.registration_form_cpass.data=''

#         # redirect page
#         return redirect(url_for('main.login'))
#     return render_template('registration.html', form=form)


#------------------------------------------------------------- about
@main.route('/about/')
def about():
    return render_template('about.html')


#------------------------------------------------------------- feedback
@main.route('/feedback')
def feedback():
    return render_template('feedback.html')

# ------------------------------------------------------------ user
# @main.route('/user/')
# @main.route('/user/<user_name>')
# def user(user_name):
#     return render_template('user.html', user_name = user_name)

app/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
<div class="container py-5">
    <h1 class="d-flex justify-content-center">About Us</h1>
        <hr>
    <div class="row my-5 py-2">
        <div class="col-md-5 col-sm-12">
            <img class="my-3 about-img img-fluid" src="{{ url_for('static', filename='res/about1.png') }}" alt="">
        </div>
        <div class="col-md-7 col-sm-12">
            <div class="p-2 my-3">
                <p><a href="{{ url_for('main.index') }}"><strong>Tech Diaries</strong></a> is an India-based technical blogging page. Our motive is to serve quality content among enthusiast developers.</p>
                <p>Through TechDiaries we want to build a platform to learn, develop skill and to contribute the socity.</p>
                <p>
                    Here is what we going to serve you- <br>
                    <ul>
                        <li>A growing community with full of tech enthusiasts.</li>
                        <li>Quality content, and real world problems.</li>
                        <li>Explore and deep drive into technology.</li>
                        <li>Open source enviornment, for better development of this site.</li>
                    </ul>
                </p>
                <p><strong>Contact us: </strong><a href="mailto:techdiaries.blog@gmail.com">techdiaries.blog@gmail.com</a>
                </p>
            </div>
        </div>
    </div>
    <h1 id="our_team" class="d-flex justify-content-center">Our Team</h1>
    <hr>
    <div class="row py-5">
        <div class="col-md-4">
            <div align="center" class="card">
                <div class="card-body">
                    <img class="user-profile rounded-circle" src="https://avatars.githubusercontent.com/u/64000509?v=4"
                        alt="">
                    <h4>Suvasish Das</h4>
                    <hr>
                    <span class="badge">Founder</span>
                    <span class="badge">Content writer</span>
                    <span class="badge">Developer</span>
                    <p class="py-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, expedita
                        adipisci debitis mollitia asperiores sequi pariatur ad deserunt sed repellendus!</p>
                    <hr>
                    <a href="https://twitter.com/Suvasis38993551"><img class="TD-icons mx-2" width="30px"
                            src="{{ url_for('static', filename='/res/twitter_icon.svg') }}"></a>
                    <a href="https://www.linkedin.com/in/suvasish-das-73862b1a0/"><img class="TD-icons mx-2" width="30px"
                            src="{{ url_for('static', filename='/res/linkedin_icon.svg') }}"></a>
                </div>
            </div>
        </div>

        <!-- <div class="col-md-4">
            <div align="center" class="card">
                <div class="card-body">
                    <img class="user-profile rounded-circle"
                        src="https://avatars.githubusercontent.com/u/64000509?v=4" alt="">
                    <h4>Lorem, ipsum.</h4>
                    <hr>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat, eveniet!</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div align="center" class="card">
                <div class="card-body">
                    <img class="user-profile rounded-circle"
                        src="https://avatars.githubusercontent.com/u/64000509?v=4" alt="">
                    <h4>Lorem, ipsum.</h4>
                    <hr>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat, eveniet!</p>
                </div>
            </div>
        </div> -->
    </div>

    <h1 id="our_team" class="d-flex justify-content-center">Donate</h1>
    <hr>
    <div class="row py-5">
        <div class="col-md-6">
        </div>
        <div class="col-md-6">
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam vitae cupiditate praesentium dicta consequatur maiores, fugiat dolore a asperiores corporis!</p>
        </div>
    </div>

    <h1 id="our_team" class="d-flex justify-content-center">Contribute</h1>
    <hr>
    <div class="row py-5">
        <div align="center" class="col-md-6">
            <img class="about-img img-fluid" src="{{ url_for('static', filename='res/about_github.png') }}" alt="">
        </div>
        <div class="py-3 col-md-6">
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magnam vitae cupiditate praesentium dicta consequatur maiores, fugiat dolore a asperiores corporis!</p>
            <div>
                <strong>Fork me on github </strong>
                <a class="TD-icons" href=""><img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white"></a>
            </div>
            
        </div>
    </div>

</div>
{% endblock %}

app/templates/admin.html
{% extends 'base.html' %}
{% block title %}Admin{% endblock %}
{% block content %}
<div class="p-5 container">
    <div class="row">
        <div class="col-md-7 py-3">
            <h1>Admin Login</h1>
            <h4>Welcome to <a href="{{ url_for('main.index') }}"><strong>Tech Diaries</strong></a></h4>
            <hr>
            <p>What can admin do:
            <ul>
                <li>Create blog post</li>
                <li>Reply comments</li>
                <li>Get SEO for blog post</li>
            </ul>
            </p>
        </div>
        <div class="col-md-5">
            <div class="card py-5 p-2">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.login_form_id(class='m-2 p-2 form-input', type='text', placeholder='Admin Id') }}
                    {{ form.login_form_pass(class='m-2 p-2 form-input', type='password', placeholder='Password') }}
                    <br>
                    {{ form.login_form_submit(class='m-2 TD_btn') }}
                </form>
            </div>
            <p class="p-2"><a href=""><strong>Contact us</strong></a> to become an Author</p>
        </div>
    </div>
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='res/favicon.png') }}">
    <!-- google fonts -->

    <!-- title -->
    <title>{% block title %}{% endblock %} | Tech Diaries</title>
</head>

<body>
    <!-- navbar -->
    <nav class="p-0 navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <span class="logo1">
                    <span class="logo-inner-p1"><strong>Tech</strong></span>
                    <span class="logo-inner-p2"><strong>Diaries</strong></span>
                </span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('main.about') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('main.blog') }}">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Series</a>
                    </li>
                    <li class="nav-link">
                        |
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('main.feedback') }}">Feedback</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="px-2" type="search" placeholder="search" aria-label="Search">
                    <a href=""><img class="px-1" src="{{ url_for('static', filename='/res/search_icon_white.svg') }}"
                            alt=""></a>

                    <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button> -->
                </form>
            </div>
        </div>
    </nav>

    <main>
        <!-- dynamic content goes here -->
        {% block content %} {% endblock %}
    </main>

    <!-- footer -->
    <section class="TD_footer">
        <footer class="container">
            <div class="logo">
                <a href="">
                    <h2><strong>techdiaries.in</strong></h2>
                </a>
            </div><br>
            <div class="row">
                <div class="col-md-4 col-sm-12">
                    <ul>
                        <li>
                            <h5>About</h1>
                        </li>
                        <hr width="50%">
                        <a href="">
                            <li>Tech Diaries</li>
                        </a>
                        <a href="">
                            <li>Become an Auth</li>
                        </a>
                        <a href="">
                            <li>Contact Us</li>
                        </a>
                        <a href="">
                            <li>Our Team</li>
                        </a>
                    </ul>
                </div>
                <div class="col-md-4 col-sm-12">
                    <ul>
                        <li>
                            <h5>Legal</h5>
                        </li>
                        <hr width="50%">
                        <a href="">
                            <li>Privacy Policy</li>
                        </a>
                        <a href="">
                            <li>Terms and Service</li>
                        </a>
                    </ul>
                </div>
                <div align="center" class="col-md-4 col-sm-12 td_footer_link">
                    <a class="TD-icons" href=""><img width="30px" src="{{ url_for('static', filename='/res/twitter_icon.svg') }}"></a>
                    <a class="TD-icons" href=""><img width="30px" src="{{ url_for('static', filename='/res/linkedin_icon.svg') }}"></a>
                    <a class="TD-icons" href=""><img width="30px" src="{{ url_for('static', filename='/res/facebook_icon.svg') }}"></a>
                    <a class="TD-icons" href=""><img width="30px" src="{{ url_for('static', filename='/res/reddit_icon.svg') }}"></a>
                </div>
            </div>
            <hr>
            <div align="center" class="copyright">
                copyright © 2020-21 | <a href=""><strong>techdiaries.in</strong></a> | All Rights Reserved
                <br>
                version 1.0
            </div>
        </footer>
    </section>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/blog.html
{% extends 'base.html' %}
{% block title %}All posts{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-sm-12 align-items-stretch">
            <h4>All posts</h4>
            <hr>
            <a href="">
                <article>
                    <div class="card">
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-4">
                                <img class="img-fluid card-image"
                                    src="{{ url_for('static', filename='res/demo.png') }}"
                                    alt="">
                            </div>
                            <div class="col-md-8 col-sm-8 col-8">
                                <div class="card-body">
                                    <h4 class="c-red">this is title</h4>
                                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt enim
                                        magnam temporibus odit. Nobis, hic?Lorem ipsum dolor sit, amet
                                        consectetur adipisicing elit. At, repudiandae.</p>

                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </a>
            <div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-end">
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="col-md-4 col-sm-12">
            <div>
                <h4>Popular tags</h4>
                <hr>
                <a href=""><span class="badge">badge</span></a>

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/feedback.html
{% extends 'base.html' %}
{% block title %}Feedback{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-8">
            <form method="POST">
                <input placeholder="email" class="p-2 m-2" type="text">
                <input placeholder="name" class="p-2 m-2" type="text">
                <input placeholder="feedback" class="p-2 m-2 form-input-100" type="text">
                <button>Send</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<!-- section1 -->
<section class="section1">
    <div class="container">
        <div class="row">
            <!-- 1st carousel -->
            <div class="col-md-8 col-sm-6">
                <a href="#">
                    <div class="card">
                        <img class="carousel-1 card-img" src="{{ url_for('static', filename='res/about1.png') }}" alt="">
                        <div class="card-img-overlay">
                            <span class="card-title carousel-title">Card title blog title</span><br>
                            <span class="card-text carousel-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</span>
                        </div>
                    </div>
                </a>
            </div>

            <!-- 2nd 3rd carousel -->
            <div class="col-md-4 col-sm-6">
                <a href="">
                    <div class="card">
                        <img class="carousel-23" src="{{ url_for('static', filename='res/about1.png') }}" class="card-img" alt="">
                        <div class="card-img-overlay">
                            <span class="card-title carousel-title">Card title</span><br>
                            <span class="card-text carousel-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</span>
                        </div>
                    </div>
                </a>
                <a href="">
                    <div class="card">
                        <img class="carousel-23" src="{{ url_for('static', filename='res/demo.png') }}" class="card-img" alt="">
                        <div class="card-img-overlay">
                            <span class="card-title carousel-title">Card title</span><br>
                            <span class="card-text carousel-text">This is a wider card with supporting text below as a natural lead bit longer.</span>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

<!-- section2 -->
<section class="section2">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12 align-items-stretch">
                <h4>Featured post</h4>
                <hr>

                <a href="">
                    <article>
                        <div class="card">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-4">
                                    <img class="img-fluid card-image" src="{{ url_for('static', filename='res/demo.png') }}" alt="">
                                </div>
                                <div class="col-md-8 col-sm-8 col-8">
                                    <div class="card-body">
                                        <h4 class="c-red">this is title</h4>
                                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt enim magnam temporibus odit. Nobis, hic?Lorem ipsum dolor sit, amet consectetur adipisicing elit. At, repudiandae.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </article>
                </a>

                <div>
                    <button>Find more</button><br><br>
                </div>
            </div>
            <div class="col-md-4 col-sm-12">
                <div>
                    <a href=""><img class="twitter_logo px-3" height="30px"
                            src="{{ url_for('static', filename='res/twitter_logo_white.svg') }}" alt=""></a>
                    <a href=""><img class="linkedin_logo px-3" height="30px"
                            src="{{ url_for('static', filename='res/linkedin_logo_white.svg') }}" alt=""></a>
                    <a href=""><img class="reddit_logo px-3" height="30px"
                            src="{{ url_for('static', filename='res/reddit_logo_white.svg') }}" alt=""></a>
                </div>
                <div class="py-3">
                    <h4>Popular tags</h4>
                    <hr>
                    <a href=""><span class="badge">badge</span></a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="p-5 container">
    <div class="row">
        <div class="col-md-7 py-3">
            <h1>User Login</h1>
            <h4>Welcome to <a href="{{ url_for('main.index') }}"><strong>Tech Diaries</strong></a></h4>
            <hr>
            <p>Create account and get those benifites:
            <ul>
                <li>Comment on post</li>
                <li>Get email notification</li>
                <li>Get chance to become Author</li>
            </ul>
            </p>
        </div>
        <div class="col-md-5">
            <div class="card py-5 p-2">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.login_form_email(class='m-2 p-2', type='email', placeholder='Email') }}
                    {{ form.login_form_pass(class='m-2 p-2', type='password', placeholder='password') }}
                    <br>
                    {{ form.login_form_submit(class='m-2 TD_btn') }}
                </form>
            </div>
            <p class="p-2"><a href="{{ url_for('main.registration') }}">Create account</a></p>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user.html
{% extends 'base.html' %}
{% block title %}User account{% endblock %}
{% block content %}
    <p>Hello {{ user_name }}</p>
{% endblock %}